version: '2'
services:
    randoricm-app:
        image: randoricm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://randoricm-mysql:3306/randoricm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    randoricm-mysql:
        extends:
            file: mysql.yml
            service: randoricm-mysql
